Feat modal dialog security #8692vbmfu
WeFriiends/WeFriiendsWeb pull request #18
Opened 2023-10-24 10:13 UTC by marrine013

## Изменения в ветке modal-dialog:

### Добавлена папка styles:

#### createTheme.js -

кастомизация стилей MUI - шрифт по умолчанию (теперь везде Inter, как в макете), primary color

#### commonStyles.js -

предлагаю сдеать такой файл для общих стилей приложения, чтобы не было повторов стилей в компонентах (заголовки, кнопки и пр.)

### Добавлена папка UI

для UI компонентов, пока там только

#### ModalDialog -

компонент для вывода диалогового окна.

Вызвать его сейчас можно со странички /testmodal - пока не знала, куда его прикручивать

### Добавлен компонент Security - Delete, Block user

### добавлен dialogContext

для окрытия/закрытия диалогового окна из вложенных компонентов

### Изменения в файлах

- изменен код в index.js для подключения контекста для диалогового окна и кастомизированной темы

- в .eslintrc добавила "prettier/prettier": ["error", { "endOfLine": "auto" }] чтоб не сыпались ошибки про CR

2023-10-24 14:11 UTC, LyubovSugak commented
Попрошу расширение изменить на ts. Пишем, используя typescript

2023-10-24 14:12 UTC, LyubovSugak requested changes

2023-10-24 14:12 UTC, LyubovSugak commented on src/UI/TestModal.js
> +    <div>
Можно убрать div.

2023-10-25 10:25 UTC, LyubovSugak commented
the folder `UI` change plz to `common`, and to have consistent folder naming we use lowercase

2023-10-25 10:35 UTC, LyubovSugak requested changes

2023-10-25 10:35 UTC, LyubovSugak commented on src/App.js
> +import TestModal from './UI/TestModal'
TBH i will not accept to merge to master test files

2023-10-25 10:35 UTC, LyubovSugak commented on src/components/security/Security.js
> +  const handleStepChange = (step) => {
tbh it looks for me weird, why you need setTimeOut. Could you explain plz

2023-10-25 11:22 UTC, marrine013 commented on src/App.js
> +import TestModal from './UI/TestModal'
этот файл делался для удобства тестирования, я его уберу, не вопрос

2023-10-25 11:22 UTC, marrine013 commented on src/UI/TestModal.js
> +    <div>
уберу файл :)

2023-10-25 11:25 UTC, marrine013 commented on src/components/security/Security.js
> +  const handleStepChange = (step) => {
поставила, чтобы замедлить переход между экранами и чтоб видна была анимация кнопок - он происходил слишком быстро, вообще трудно было понять пользователю (мне), что экран поменялся. С этой же целью добавила Backdrop

2023-11-02 16:49 UTC, LyubovSugak commented on src/common/ModalDialog.tsx
> +const StyledDialogContent = styled(DialogContent)(({ theme }) => ({
Посмотри в других pr, используется makeStyles. Удобнее читать, когда хук после компонента находится, внизу файла

2023-11-02 16:57 UTC, LyubovSugak commented on src/components/security/UserBlocked.tsx
> +interface UserBlockedProps {
Может будет желание сделать дженерик тип, тк UserDeletedProps похожий

2023-11-02 16:58 UTC, LyubovSugak commented on src/components/security/Security.js
> +  const handleStepChange = (step) => {
Может имеет смысл с точки зрения UX сделать изменения?

2023-11-03 07:58 UTC, marrine013 commented on src/components/security/Security.js
> +  const handleStepChange = (step) => {
не понимаю, что имеется в виду

2023-11-03 15:54 UTC, marrine013 commented on src/components/security/UserBlocked.tsx
> +interface UserBlockedProps {
как там сделать дженерик я не придумала, сделала общие компоненты UserAction для удаления и блокировки и ActionConfirm для подтверждения удаления и блокировки

2023-12-28 10:35 UTC, LyubovSugak approved these changes

2023-12-28 10:36 UTC, merged