fullName filling out
WeFriiends/WeFriiendsWeb pull request #36
Opened 2024-01-26 01:14 UTC by SofiaPetinova

I created a new pull request, because prev. wasn't updated with current changes and I just messed up everything. I didn't closed prev. PR yet, I just thought maybe you want to see the past comments.

2024-01-29 17:39 UTC, Svitlana-G commented on src/components/firstProfile/NameProfile.tsx
> +// import { v4 as uuidv4 } from 'uuid'
Please delete comments

2024-01-29 17:39 UTC, Svitlana-G commented on src/components/firstProfile/NameProfile.tsx
> +  // }
Please delete comments

2024-01-29 17:39 UTC, Svitlana-G commented on src/components/firstProfile/NameProfile.tsx
> +        await axios.post('api/addName', fullName)
I think we save the data at the end when all the fields in the profile are filled in. I propose to clarify this point

2024-01-29 17:39 UTC, Svitlana-G commented on src/routes/index.tsx
> +  },
I think it should be as a child in the  'user' path

2024-01-29 17:39 UTC, Svitlana-G commented on src/styles/firstProfileStyles.tsx
> +    mainBox: {
Please use commonStyles

2024-01-29 17:39 UTC, Svitlana-G commented on src/styles/firstProfileStyles.tsx
> +    title: {
Please use commonStyles

2024-01-29 17:39 UTC, Svitlana-G commented on src/styles/firstProfileStyles.tsx
> +    nextButton: {
It would be good to put it in the commonStyles

2024-02-06 12:12 UTC, LyubovSugak commented on src/components/firstProfile/NameProfile.tsx
> +        await axios.post('api/addName', fullName)
api calls should be moved to separate function/file in the folder action. It's a principle of splitting up app calls, business logic and presentational components. My advice to read about above principle.
Anyway as Svetlana mentioned we use local storage to store data first there

2024-02-06 12:15 UTC, LyubovSugak commented on src/components/firstProfile/NameProfile.tsx
> +        What&apos;s your name?
Typo?

2024-02-06 12:22 UTC, LyubovSugak commented on src/hooks/useProfileData.ts
> +const useProfileData = <T>(key: string, initialValue: T) => {
Nice idea to use hook, but could you refactor it to make generic and use in other components. Plz thing about naming (in useState),change to smth meaningful

2024-02-06 12:33 UTC, LyubovSugak commented on src/components/firstProfile/NameProfile.tsx
> +    if (fullName.trim() === '') {
Plz refactor lines underneath, I don't think you need spaghetti here

2024-02-20 03:39 UTC, SofiaPetinova commented on src/components/firstProfile/NameProfile.tsx
> +        What&apos;s your name?
нет, когда я ставлю обычный ', то выходит ошибка то ли eslint, то ли prettier. Погуглила и предлагается такой вариант.

2024-02-20 03:41 UTC, SofiaPetinova commented on src/components/firstProfile/NameProfile.tsx
> +        await axios.post('api/addName', fullName)
api calls удаляю тогда вообще?

2024-02-20 03:42 UTC, SofiaPetinova commented on src/hooks/useProfileData.ts
> +const useProfileData = <T>(key: string, initialValue: T) => {
это вообще удаляю? тк ты мне написала оставить только верстку и логику кнопка

2024-03-07 19:40 UTC, LyubovSugak requested changes

2024-03-07 19:40 UTC, LyubovSugak commented on src/components/firstProfile/NameProfile.tsx
> +      <form onSubmit={handleSubmit}>
don't need `form` here. Clicking on the button will add data to local storage. The form usually is needed to send data via API

2024-03-07 19:40 UTC, LyubovSugak commented on src/components/firstProfile/NameProfile.tsx
> +          <Button
you can remove button, component `Name profile`will be shown via generic component carousel

2024-03-07 19:40 UTC, LyubovSugak commented on src/components/firstProfile/NameProfile.tsx
> +          <Typography variant="h2" className={classes.dot}>
also plz remove dots

2024-03-07 19:40 UTC, LyubovSugak commented on src/components/firstProfile/NameProfile.tsx
> +const useStyles = makeStyles()(() => {
After refactoring, remove plz unused code in style hook

2024-03-07 19:40 UTC, LyubovSugak commented on src/routes/index.tsx
> +      {
plz remove after the route, there will be only one route for the whole Profile

2024-03-12 02:30 UTC, closed without merging