Wfw 8696mju1r front functional for backend
WeFriiends/WeFriiendsWeb pull request #86
Opened 2024-11-30 19:46 UTC by Enigma2017

2024-12-03 21:08 UTC, Svitlana-G requested changes
In API we only pass the data, all processing is done in the component. Please, make changes in profile.ts

Please, delete all console.log

2024-12-03 21:08 UTC, Svitlana-G commented on src/utils/localStorage.ts
> +  return result
Please return the code back

2024-12-03 21:10 UTC, Svitlana-G commented on src/components/firstProfile/uploadPhotos/UploadSlot.tsx
> +            fileName: file.name,
Why do you need fileName?

2024-12-21 12:19 UTC, Enigma2017 commented on src/actions/profile.ts
> +  const response = await fetch('http://localhost:8080/api/profile', {
+done

2024-12-21 12:19 UTC, Enigma2017 commented on src/utils/localStorage.ts
> +  return result
+done

2025-01-13 15:14 UTC, Svitlana-G requested changes

2025-01-27 12:32 UTC, Enigma2017 commented on src/components/firstProfile/uploadPhotos/UploadPhotos.tsx
> +  interface Window {
The declare global block is used to extend the global window object by adding a custom property choosenFiles with the type File[].
Why is it needed?
TypeScript Type Safety: By default, window doesn't have a choosenFiles property. This declaration informs TypeScript about its existence and type, preventing errors.
Global Access: It allows choosenFiles to be accessible globally, useful for scenarios where selected files need to be shared across components.
Prevent Errors: Ensures proper typing and prevents accidental assignment of incorrect types to window.choosenFiles

2025-01-27 12:44 UTC, Enigma2017 commented on src/actions/profile.ts
> +interface Location {
done

2025-01-27 12:48 UTC, Enigma2017 commented on src/actions/profile.ts
> +  const response = await axios.post(API_BASE_URL, formData, {
+done

2025-01-31 16:24 UTC, Svitlana-G commented on src/actions/profile.ts
> +function base64ToBlob(base64: string, mimeType: string): Blob {
Removed the base64 upload. Please check if everything is working correctly

2025-02-10 20:29 UTC, merged